apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: 30secs
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - "-c"
        - "while true; do echo hello; sleep 10;done"
        image: busybox
        name: 30secs
        resources: {}
      restartPolicy: Never
status: {}
