apiVersion: batch/v1
kind: Job
metadata:
  name: 30secs
  namespace: default
spec:
  #activeDeadlineSeconds: 30
  completions: 5
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: 30secs
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello; sleep 30;echo world
        image: busybox
        imagePullPolicy: Always
        name: 30secs
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

