apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-notexist
  name: busybox-notexist
spec:
  containers:
  - command:
    - /bin/sh
    - -c 
    - ls /notexist
    image: busybox
    name: busybox-notexist
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
