apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 300
    image: busybox
    name: busybox1
    volumeMounts:
    - mountPath: /etc/foo
      name: foo-volume

  - command:
    - /bin/sh
    - -c
    - sleep 300
    image: busybox
    name: busybox2
    volumeMounts:
    - mountPath: /etc/foo
      name: foo-volume

  volumes:
  - name: foo-volume
    emptyDir:
      sizeLimit: 500Mi

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
