apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - command: ["/bin/sh", "-c"]
    args: ["echo hello; sleep 3600"]
    image: busybox
    name: busybox
    resources: {}
  - command: ["/bin/sh", "-c"]
    args: ["echo hello; sleep 3600"]
    image: busybox
    name: busybox2
    resources: {}
