apiVersion: batch/v1
kind: CronJob
metadata:
  name: busybox
  namespace: default
spec:
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 17
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: busybox
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            imagePullPolicy: Always
            name: busybox
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
