apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: granted-pods
  
spec:
  podSelector:
    matchLabels:
      access: granted
  policyTypes:
  - Ingress
  ingress: 
  - from: 
    - podSelector:
        matchLabels:
          access: granted



