apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: limitrange
spec:
  limits:
  - default: # this section defines default limits
      memory: 500Mi
    defaultRequest: # this section defines default requests
      memory: 100Mi
    max: # max and min define the limit range
      memory: "500Mi"
    min:
      memory: 100Mi
    type: Container
