apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: limitrange
spec:
  limits:
  - default: # this section defines default limits
      memory: 500m
    defaultRequest: # this section defines default requests
      memory: 100m
    max: # max and min define the limit range
      memory: "500m"
    min:
      memory: 100m
    type: Container
