apiVersion: v1
kind: Pod
metadata:
  name: security-context-nginx-net-admin
spec:
  containers:
  - name: sec-ctx-nginx-net-admin
    image: nginx
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]