apiVersion: v1
kind: Pod
metadata:
  name: nginx-anotherone
spec:
  containers:
    - name: nginx-anotherone
      image: nginx
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: option1
          valueFrom:
            configMapKeyRef:
              name: anotherone
              key: var6

        - name: option2
          valueFrom:
            configMapKeyRef:
              name: anotherone
              key: var7