apiVersion: v1
kind: Pod
metadata:
 
  labels:
    run: nginx-sa
  name: nginx-sa
  namespace: default

spec:
  serviceAccountName: myuser

  containers:
    
  - image: nginx
    imagePullPolicy: Always
    name: nginx-sa
 