apiVersion: v1
kind: Pod
metadata:
  name: consumer-ssh-pod
  namespace: secret-ops
spec:
  volumes:
    - name: ssh-volume
      secret:
        secretName: my-secret
  containers:
    - name: consumer-ssh-pod
      image: nginx
      volumeMounts:
        - name: ssh-volume
          readOnly: true
          mountPath: "/var/app"

