apiVersion: v1
kind: Pod
metadata:
  name: nginx-foo
spec:
  containers:
  - name: nginx-foo
    image: nginx
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret2
     