apiVersion: v1
kind: Pod
metadata:
  name: consumer
  namespace: secret-ops
spec:
  containers:
  - name: consumer
    image: nginx
    env:
    - name: APIKEY
      valueFrom:
        secretKeyRef:
          name: ext-service-secret
          key: API_KEY