apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: option
          valueFrom:
            configMapKeyRef:
              name: options
              key: var5
  restartPolicy: Never

