apiVersion: v1
kind: Pod
metadata:
  labels:
    test: nginx-liveness-test
  name: nginx-liveness
spec:
  containers:
  - name: nginx-liveness
    image: nginx
    livenessProbe:
      exec:
        command:
        - ls
        - /tmp
      initialDelaySeconds: 5
      periodSeconds: 5
