apiVersion: v1
kind: Pod
metadata:
  name: security-context-nginx
spec:
  securityContext:
    runAsUser: 101
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-nginx
    image: nginx

