apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm-vol
spec:
  containers:
    - name: nginx-cm
      image: nginx
      command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']
      volumeMounts:
        - name: configmap-vol
          mountPath: /etc/lala
  volumes:
    - name: configmap-vol
      configMap:
        name: cmvolume

