apiVersion: v1
kind: Pod
metadata:
  name: nginx-env-secret
spec:
  containers:
  - name: nginx-env-secret
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret2
          key: admin
