apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo
  namespace: one
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "2Gi"
        cpu: "1"
      requests:
        memory: "1Gi"
        cpu: "0.5"